### PR TITLE
Ordered maps

### PR DESCRIPTION
**Pull request by TomWright**
This is my first attempt at supporting ordered maps, starting with JSON.

It's become apparent there's no way to achieve this functionality unless I write my own encoders + decoders for all supported file formats.

This is a very large undertaking, and given the fact that ordered JSON isn't even a part of the JSON spec itself I'm not sure it's worth doing due to the amount of complexity it adds to the project.

Of course this is only regarding JSON as the majority of my tests are placed around it and it gave me an easy way to check a variety of use-cases quickly and easily, but may well transfer to other data formats.

### CODE REVIEW

**Comment by joshuadmatthews** [comment]
I think it’s worth doing, if only just iteratively one format at a type. Open source community can implement the formats that are important to them. I just need yaml, and don’t mind working on that following the patterns you lay out here. Would an iterative process work here?

I don’t see how this can be avoided, dasel is a great concept but preserving key order is a must have feature for a tool like this. Nobody wants their entire document mangled.

**Comment by TomWright** [comment]
Thanks for the feedback @joshuadmatthews. 

I believe the ordered map implementation here allows us to deal with ordered maps internally so the addition of formatters at a later date shouldn't be a problem.

I'll take a look at a yaml parser implementation when I get the chance.

**Comment by TomWright** [comment]
I just realised that a custom parser implementation will be able to keep hold of all metadata, including comments.

**Comment by TomWright** [comment]
I have a working implementation for JSON...
```bash
// New logic...
$ echo '{"z":1,"a":2,"c":3}' | go run cmd/dasel/main.go -r json 
{
  "z": 1,
  "a": 2,
  "c": 3
}
// Existing logic...
$ echo '{"z":1,"a":2,"c":3}' | dasel -r json                   
{
  "a": 2,
  "c": 3,
  "z": 1
}

```

**Comment by joshuadmatthews** [comment]
You rock @TomWright ! Thanks for pushing forward!

**Comment by TomWright** [comment]
This PR has been sitting around for a long time - I'm merging it in now as it's update to date with master and all tests are passing.

**Pull request merged**
