### PR TITLE
Fixes the missing null values in the output

### LINKED ISSUE #316: The fields with null value just disappear in the output
**Describe the bug**

Fields with a value of `null` are not available in the output.

**To Reproduce**

actual data

```json
{
  "a": "alice",
  "b": null,
  "c": [
    {
      "d": 9,
      "e": null
    }
  ]
}
```

```
$ dasel -r json -f data.json
```

actual output:

```json
{
  "a": "alice",
  "c": [
    {
      "d": 9
    }
  ]
}
```

expected output:

```json
{
  "a": "alice",
  "b": null,
  "c": [
    {
      "d": 9,
      "e": null
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by semihbkgr**
fixes #316

### CODE REVIEW

**Comment by TomWright** [comment]
The change looks good - could I ask you to add a test for this please? Just the example you gave in the original issue would be good enough.

You can add a top level test here: https://github.com/TomWright/dasel/blob/3b466e80eabf70b6b39aadb99e43f5fff57ea2ae/internal/command/select_test.go#L41

**Comment by semihbkgr** [comment]
Of course I will add.

**Review by TomWright — APPROVED** [review]

**Review by TomWright — CHANGES_REQUESTED** [review]
I'll look at the failing test tomorrow

**Comment by semihbkgr** [comment]
Tests started failing after Ordered maps #289 merge.

**Comment by semihbkgr** [comment]
I slightly debugged to find out which changes cause to fail. Seems like It is the same reason as #296.

**Comment by TomWright** [comment]
OK thanks - I'll take a look to see what I broke with that PR and merge this when resolved 👍

**Review by TomWright — APPROVED** [review]

**Comment by TomWright** [comment]
Hey @semihbkgr, sorry for the delay.

I've fixed the issue - the root cause was a new data structure being used to allow for ordered maps. I just had to replicate the same logic in another place.

Thanks for the contribution!

**Pull request merged**
