### PR TITLE
Quote map keys when encoding TOML data

### LINKED ISSUE #56: TOML: QuoteMapKeys
If you have this JSON:

~~~json
{
   "This is a": "TOML document",
   "name": "Tom Preston-Werner",
   "title": "TOML Example"
}
~~~

you get this TOML:

~~~toml
"This is a" = "TOML document"
name = "Tom Preston-Werner"
title = "TOML Example"
~~~

Current implementation is here:

https://github.com/TomWright/dasel/blob/ba2b3c0dac195b1f0b7cfaf5250c9dd55a33b0a3/internal/storage/toml.go#L29-L33

the TOML library has an option to always quote the keys:

https://pkg.go.dev/github.com/pelletier/go-toml#Encoder.QuoteMapKeys

that would produce this output:

~~~
"This is a" = "TOML document"
"name" = "Tom Preston-Werner"
"title" = "TOML Example"
~~~

basically the code could be changed to this:

~~~
enc := toml.NewEncoder(buf).QuoteMapKeys(quote)
~~~

where `quote` is a boolean that can be set by the user.

### PR DESCRIPTION
**Pull request by TomWright**
Closes #56 

This is a cosmetic change.

### CODE REVIEW

**Comment by TomWright** [comment]
This solves the "issue", but I'm still not convinced it's worth doing. Can I get some input from others who use TOML more often?

**Comment by TomWright** [comment]
Perhaps a flag could enable this feature.

**Comment by 89z** [comment]
When I posted the issue, I was looking a different ways to solve a problem. Since then I decided against using TOML. So one option would be to close the PR. If the PR is to remain open or be merged, here is my feedback. The current standard:

https://toml.io/en/v1.0.0-rc.3

only quotes when needed. So I would say the default should match that. An option could be added to always quote, or maybe read from environment variable.

**Comment by TomWright** [comment]
I'm just going to close this PR then. If anyone else needs this functionality it can be enabled with a flag but for now it seems unnecessary.

Thanks for the feedback 👍

**Pull request closed without merging**
